services:
  server:
    container_name: devsync-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - DevSync
    ports:
      - "3000:3000"

  client:
    container_name: devsync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - DevSync
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
  DevSync:
    driver: bridge